export const BASE_COMPONENT = [
  'ElInput',
  'ElForm',
  'ElFormItem',
  'ElSelect',
  'ElOption',
  'ElRadioGroup',
  'ElRadio',
  'ElCheckbox',
  'ElCheckboxGroup',
  'ElSwitch',
  'ElDatePicker',
  'ElTimePicker',
  'ElTimeSelect',
  'ElCascader',
]